spring.sql.init.mode=always
spring.datasource.url=jdbc:h2:mem:filmorate;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
logging.level.org.zalando.logbook=TRACE
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) %clr(---){faint} %clr(%msg%n){%p}
