--Справочники
CREATE TABLE IF NOT EXISTS MPA_Ratings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Genres
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO MPA_Ratings (name)
VALUES ('G'), ('PG'), ('PG-13'), ('R'), ('NC-17');

INSERT INTO Genres (name)
VALUES ('Комедия'), ('Драма'), ('Мультфильм'), ('Триллер'), ('Документальный'),
('Боевик');

CREATE TABLE IF NOT EXISTS Directors (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE
);


--Главные сущности (модели)
CREATE TABLE IF NOT EXISTS Users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    login    VARCHAR(255) NOT NULL UNIQUE,
    name     VARCHAR(255),
    birthday DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS Films
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT         NOT NULL,
    releaseDate DATE,
    duration    BIGINT       NOT NULL,
    rating_id   BIGINT       NOT NULL REFERENCES MPA_Ratings (id),
    director_id BIGINT       REFERENCES Directors(id)
);

CREATE TABLE IF NOT EXISTS Reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     VARCHAR(255),
    isPositive  BOOLEAN,
    user_id     BIGINT NOT NULL REFERENCES Users(id),
    film_id     BIGINT NOT NULL REFERENCES Films(id),
    useful      BIGINT
);

CREATE TABLE IF NOT EXISTS Review_Likes
(
    review_id BIGINT NOT NULL REFERENCES Reviews (id),
    user_id BIGINT NOT NULL REFERENCES Users (id),
    PRIMARY KEY (review_id, user_id)
);

CREATE TABLE IF NOT EXISTS Review_Dislikes
(
    review_id BIGINT NOT NULL REFERENCES Reviews (id),
    user_id BIGINT NOT NULL REFERENCES Users (id),
    PRIMARY KEY (review_id, user_id)
);

--Связующие таблицы
CREATE TABLE IF NOT EXISTS Friends
(
    user_id   BIGINT      NOT NULL REFERENCES Users (id),
    friend_id BIGINT      NOT NULL REFERENCES Users (id),
    status    VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS Film_Likes
(
    film_id BIGINT NOT NULL REFERENCES Films (id),
    user_id BIGINT NOT NULL REFERENCES Users (id),
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS Film_Genres
(
    film_id  BIGINT NOT NULL REFERENCES Films (id),
    genre_id BIGINT NOT NULL REFERENCES Genres (id),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS Events
(
    event_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP   NOT NULL,
    user_id    BIGINT      NOT NULL REFERENCES Users (id),
    event_type VARCHAR(20) NOT NULL,
    operation  VARCHAR(20) NOT NULL,
    entity_id  BIGINT      NOT NULL
);