--Справочники
CREATE TABLE MPA_Ratings
(
    rating_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE Genres
(
    genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100) NOT NULL UNIQUE
);

--Главные сущности (модели)
CREATE TABLE Users
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    login    VARCHAR(255) NOT NULL,
    name     VARCHAR(255),
    birthday DATE
);

CREATE TABLE Films
(
    film_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT         NOT NULL,
    releaseDate DATE,
    duration    BIGINT       NOT NULL,
    rating_id   BIGINT       NOT NULL REFERENCES MPA_Ratings (rating_id)
);

--Связующие таблицы
CREATE TABLE Friends
(
    user_id   BIGINT      NOT NULL REFERENCES Users (user_id),
    friend_id BIGINT      NOT NULL REFERENCES Users (user_id),
    status    VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE Film_Likes
(
    film_id BIGINT NOT NULL REFERENCES Films (film_id),
    user_id BIGINT NOT NULL REFERENCES Users (user_id),
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE Film_Genres
(
    film_id  BIGINT NOT NULL REFERENCES Films (film_id),
    genre_id BIGINT NOT NULL REFERENCES Genres (genre_id),
    PRIMARY KEY (film_id, genre_id)
);